### ISSUE TITLE
The guest would be broken down when I intentionally made some mistakes with the ZNS SSD simulated by FEMU.

### ISSUE THREAD

**Issue by Konna619** [vtess/FEMU#103]
The first zone's wptr is modified to 0x1 when I run command ` echo "hello" | sudo nvme zns zone-append /dev/nvme1n1 -s 0 -z 512 `.
Then I run command ` echo "goodbye" | sudo nvme write /dev/nvme1n1 -s 0 -z 512 `.
The LBA where I write is smaller than wptr of first zone so the write will not succeed and an error is expected.
But at this point, the guest is stuck!

When I do the same thing to ZNS SSD simulated by QEMU, it can return correct error message:
```
NVMe status: Zone Invalid Write: The write to zone was not at the write pointer offset(0x41bc)
```

**Comment by hansenidden18** [comment]
Hi,
Did you encountered any error at all or it just stuck? Or did the stuck happen after the error like the image below? 

![image](https://user-images.githubusercontent.com/62301187/232832602-b3636bc8-b5a6-406c-b3e3-0ea2b1f8ccaf.png)

If so, you probably need a newer guest kernel to run FEMU ZNS mode. I already tested it on Linux v5.4 (first image) and v6.1 (second image). When using Linux v5.4, the guest OS will get stuck after the error happened. On the other hand, in Linux v6.1 the guest OS will return the error and won't get stuck. 

![image](https://user-images.githubusercontent.com/62301187/232832702-bb502649-0335-45e8-a5d7-f77ddcf347cd.png)

I suggest using Linux v6.1 or higher as a starting point (i.e., download and install the Linux kernel 6.1 in the VM) since it has better ZNS support. The VM image that FEMU provided has Linux kernel v5.4 in it.

**Comment by Konna619** [comment]
Thanks for your answers!
